### ISSUE TITLE
Integrating Gitea as Source

### ISSUE THREAD

**Issue by s00500** [creativeprojects/go-selfupdate#1]
Hey @creativeprojects ,
awesome to see somebody making go-github-selfupdate more generic

What are you plans with this ? Will you keep maintaining it ?

If so I would add support for Gitea (in a PR), as your abstractions for sources and eleases already make it really straight forward to do so! (I actually started with making the updater genric for half an hour, than  procrastination and googling brought me here 😅)

Greetings,
Lukas

**Comment by creativeprojects** [comment]
Hi!
Yes, my plan is to keep maintaining it. I needed it for another project and I thought I could make it generic since I have some other stuff hosted on gitlab.

Nice to see it can get some interest 😄 

The API is probably stable enough right now, but it might change slightly before version 1 (nothing planned yet though)

So yes, if you want to add support for gitea, feel free to propose a PR

Thanks

**Comment by s00500** [comment]
Perfect, I will have a go at it in the next days, I already have on request: the DownloadReleaseAsset function will need an additional releaseID... unless I find a prettier solution

But in gitea you need to specify the release AND the asset id =D, I will start my PR

Thanks for your info!

**Comment by creativeprojects** [comment]
Yes it's fine if we need to change the signature of the method

**Comment by s00500** [comment]
I have also created a little test project on my personal gitea, also testing ECDSA signature validation, works nicely but took a little to figure out... I guess we could extend docs here a little, the crypto/ecdsa package does not provide a lot of hints on how to create its primitives from raw pem format, luckily there is the pemutil pkg :-)

**Comment by s00500** [comment]
https://git.lbsfilm.at/lbsadmin/goselfupdatetest/

**Comment by creativeprojects** [comment]
> I have also created a little test project on my personal gitea, also testing ECDSA signature validation, works nicely but took a little to figure out... I guess we could extend docs here a little, the crypto/ecdsa package does not provide a lot of hints on how to create its primitives from raw pem format, luckily there is the pemutil pkg :-)

Sorry, yes you caught me off guard. I haven't had the time to document all these things yet, I was just making it for me as a start 😄
