### ISSUE TITLE
Why not save yourself an API call for most use-cases by calling /releases/latest

### ISSUE THREAD

**Issue by AskAlice** [creativeprojects/go-selfupdate#4]
ie: https://api.github.com/repos/section/sectionctl/releases/latest

it already has all the release assets listed, so you can just download them from the url, rather than listing all releases, then finding the 'most recent one' ?

in detect.go it makes two calls to the source provider, one to list releases, and one to get the latest release and one to pick the latest release

https://github.com/creativeprojects/go-selfupdate/blob/main/detect.go#L33-L41

Then all you need to do is download the release

**Comment by creativeprojects** [comment]
Thanks!
That's a good point, although I need to make sure it's also the case for the other providers (I still need to do GitLab)

**Comment by creativeprojects** [comment]
It is actually more complicated than that:

What if a software is maintaining two (or more) streams? Let's say a v1 branch and a v2 branch.

In case a fix is made on both branches, the order of pipelines might not be guaranteed: In which case v2 could go first and v1 after. The release fix on v1 will be tagged as `latest`. In reality it's the version right before that is the latest.

The current implementation would give the v2 as an answer, whereas using the `latest` api would give the v1.

**Comment by creativeprojects** [comment]
That was a good idea but actually it's not going to work. I still need another call to the API to get a list of assets.
